name: push
on: [push, pull_request]
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  pages:
    environment: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install uv with cache enabled
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "requirements**.txt"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: 'curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep "browser_download_url.*-amd64.deb" | cut -d : -f 2,3 | tr -d \" | wget -qi - -O pandoc.deb && sudo dpkg -i pandoc.deb'
      - run: sudo apt-get install texlive texlive-latex-extra texlive-latex-recommended texlive-xetex
      - run: uv pip install -r requirements.txt
      - run: mkdocs gh-deploy --force --remote-branch main